version: '3.8'

services:

# ---------------- MYSQL ----------------
  mysql:
    image: mysql:8
    container_name: booknest-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
# ---------------- EUREKA ----------------
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  # ---------------- AUTH SERVICE ----------------
  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - mysql
      - eureka-server
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/booknest_auth
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # ---------------- BOOK SERVICE ----------------
  book-service:
    build: ./book-service
    container_name: book-service
    depends_on:
      - eureka-server
      - mysql
    ports:
      - "8086:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

    # --------------CART SERVICE --------------------
  cart-service:
      build: ./cart-service
      container_name: cart-service
      ports:
        - "8083:8083"
      depends_on:
        - eureka-server
        - mysql
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cart_db
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # ---------------- ORDER SERVICE ----------------
  order-service:
      build: ./order-service
      container_name: order-service
      ports:
        - "8084:8084"
      depends_on:
        - eureka-server
        - mysql
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/order_db
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # ---------------- WALLET SERVICE ----------------
  wallet-service:
      build: ./wallet-service
      container_name: wallet-service
      ports:
        - "8085:8085"
      depends_on:
        - eureka-server
        - mysql
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/wallet_db
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # ---------------- REVIEW SERVICE ----------------
  review-service:
      build: ./review-service
      container_name: review-service
      ports:
        - "8087:8086"
      depends_on:
        - eureka-server
        - mysql
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/review_db
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # ---------------- NOTIFICATION SERVICE ----------------
  notification-service:
      build: ./notification-service
      container_name: notification-service
      ports:
        - "8088:8087"
      depends_on:
        - eureka-server
        - mysql
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/notification_db
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # ---------------- WISHLIST SERVICE ----------------
  wishlist-service:
      build: ./wishlist-service
      container_name: wishlist-service
      ports:
        - "8089:8088"
      depends_on:
        - eureka-server
        - mysql
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/wishlist_db
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
volumes:
  mysql_data:

