server:
  port: 8085

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:mysql://mysql:3306/wallet_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

openapi:
  server:
    url: ${OPENAPI_SERVER_URL:http://localhost:8080/api/wallet}
