CREATE DATABASE IF NOT EXISTS booknest_auth;
CREATE DATABASE IF NOT EXISTS bookdb;
CREATE DATABASE IF NOT EXISTS cart_db;
CREATE DATABASE IF NOT EXISTS order_db;
CREATE DATABASE IF NOT EXISTS wallet_db;
